enhancement/mui-tag
fictadvisor/fictadvisor-web pull request #281
Opened 2023-04-01 16:43 UTC by ria0308

2023-04-07 18:21 UTC, OleksandrHumeniuk requested changes

2023-04-07 18:21 UTC, OleksandrHumeniuk commented on src/components/common/ui/tag-mui/Tag.tsx
> +  color,
Color is optional parameter, but no default value is provided

2023-04-07 18:21 UTC, OleksandrHumeniuk commented on src/components/common/ui/tag-mui/Tag.tsx
> +  size,
Size is optional parameter, but no default value is provided

2023-04-07 18:21 UTC, OleksandrHumeniuk commented on src/components/common/ui/tag-mui/Tag.tsx
> +  text?: string;
Make text parameter required

2023-04-08 18:15 UTC, OleksandrHumeniuk approved these changes

2023-04-09 20:51 UTC, andrewvitrenko approved these changes

2023-04-10 19:10 UTC, merged