feature/comment
fictadvisor/fictadvisor-web pull request #326
Opened 2023-05-16 10:47 UTC by igaryakqwe

2023-05-16 11:50 UTC, kujo205 commented on src/components/common/ui/comment/Comment.styles.ts
> +  color: '#737373'
use color from the theme

2023-05-16 11:50 UTC, kujo205 commented on src/components/common/ui/comment/Comment.styles.ts
> +  fontFamily: 'Manrope',
use font styles from the theme as well

2023-05-16 11:50 UTC, kujo205 commented on src/components/common/ui/comment/Comment.styles.ts
> +  backgroundColor: '#292929',
same with color

2023-05-16 11:50 UTC, kujo205 commented on src/components/common/ui/comment/Comment.tsx
> +const Comment = ({text, semester, year}) => {
Add interface for better types support, like that

`interface CommentProps{
text:string;
semester:string;
year:string;
}`

And u can add this interface as shown [here](https://github.com/fictadvisor/fictadvisor-web/blob/34c222fef0de24db83add29f16998e654d55f936/src/components/common/ui/alert-mui/Alert.tsx#LL39C25-L39C25)

2023-05-23 09:17 UTC, Markusplay requested changes

2023-05-23 09:17 UTC, Markusplay commented on src/components/common/ui/comment/Comment.styles.ts
> +    mobile: typography.body1,
Like in a `backgroundColor`, you can write just `body1`. Same for other typographies

2023-05-23 09:17 UTC, Markusplay commented on src/components/pages/test-pages/comment-page/CommentTestPage.styles.ts
> +export { wrapper };
Actually, it is not necessary to write export like it. You can just write `export`  before `const`, result is the same. Notice, that If you would have huge amount of styles, you will write looooong export.
P.S : same issue in Comment.styles

2023-05-24 15:54 UTC, Markusplay approved these changes

2023-05-26 16:24 UTC, merged