feature: new Input-mui (in progress)
fictadvisor/fictadvisor-web pull request #412
Opened 2023-06-19 21:32 UTC by OleksandrHumeniuk

2023-06-21 18:47 UTC, andrewvitrenko requested changes

2023-06-21 18:47 UTC, andrewvitrenko commented on src/components/common/ui/form/input-mui/Input.styles.ts
> +  // Makes only lower half of the label to have background (designers asked to do this)
add comment that it is a bug fix and if someone can fix it would be great

2023-06-21 18:47 UTC, andrewvitrenko commented on src/components/common/ui/form/input-mui/Input.tsx
> +  extends Omit<React.ComponentPropsWithoutRef<'input'>, 'size'> {
is it supposed to be default props for HTML input element? if yes, then use `HTMLProps<HTMLInputElement>`. and u don't need `Omit` cause u can override `size` prop in interface easily

2023-06-21 18:47 UTC, andrewvitrenko commented on src/components/common/ui/form/input-mui/Input.tsx
> +}
make `name` prop required, cause it is needed for formik

2023-06-21 18:47 UTC, andrewvitrenko commented on src/components/common/ui/form/input-mui/Input.tsx
> +    rest.name,
get `name` with destruction, not with `rest`. you might not need to pass to input, you can just extract `value`, and create handlers for input

2023-06-21 18:47 UTC, andrewvitrenko commented on src/components/common/ui/form/input-mui/Input.tsx
> +    const curTimer = setTimeout(() => {
is that supposed to be a debounce?

2023-06-21 18:47 UTC, andrewvitrenko commented on src/components/pages/test-pages/input-page/InputPage.tsx
> +        initialValues={{ t1: '', t2: '', t3: '', t4: '', t5: '', t6: '' }}
move that and validation to constants above component

2023-06-21 18:47 UTC, andrewvitrenko commented on src/pages/test/input.tsx
> +const MUI = () => <InputPage />;
add type that it is a `NextPage`

2023-08-15 23:11 UTC, Markusplay requested changes

2023-08-15 23:11 UTC, Markusplay commented on src/components/pages/account-page/components/general-tab/components/contacts-block/components/ContactItem.tsx
> +      <Input name={name} value={displayName} label={name} />
same question as in security tab

2023-08-15 23:11 UTC, Markusplay commented on src/components/common/ui/form/with-formik/input/FormikInput.tsx
> +const FormikDropdown: FC<FormikInputProps> = ({
maybe FormikInput :)

2023-08-15 23:11 UTC, Markusplay commented on src/components/common/ui/form/with-formik/input/FormikInput.tsx
> +      name={name}
how and why did you pass name prop if it doesn't exist in default `Input` ?

2023-08-15 23:11 UTC, Markusplay commented on src/components/pages/account-page/components/general-tab/components/contacts-block/components/ContactItem.tsx
> +      <Input name={name} value={displayName} label={name} />
It is default `Input`, why `name` is here ?

2023-08-15 23:11 UTC, Markusplay commented on src/components/common/ui/form/input-mui/util/index.ts
> +  type === InputType.SEARCH ? MagnifyingGlassIcon : null;
Firstly, you can use `&&` instead ternary operator. 
Secondly, it seems not like difficult logic to keep it in separate function util. Checkout comment in component

2023-08-15 23:11 UTC, Markusplay commented on src/components/common/ui/form/input-mui/Input.tsx
> +        startAdornment={LeftIcon && <LeftIcon />}
```suggestion
        startAdornment={type === InputType.SEARCH && MagnifyingGlassIcon}
```

2023-08-16 12:47 UTC, Yevheniy2020 commented on src/components/common/ui/form/input-mui/Input.tsx
> +        startAdornment={LeftIcon && <LeftIcon />}
![image](https://github.com/fictadvisor/fictadvisor-web/assets/68693183/2e21278d-7c1a-4e7e-9c15-8b6e210cb174)

2023-08-18 19:54 UTC, Markusplay approved these changes

2023-08-27 10:27 UTC, Markusplay requested changes

2023-08-27 10:27 UTC, Markusplay commented on src/components/common/ui/form/input-mui/Input.stories.tsx
> +Base.args = { readOnly: false, disabled: false };
`readOnly` and `disabled` are false by default, aren't they ?

2023-08-27 10:27 UTC, Markusplay commented on src/components/common/ui/form/input-mui/Input.styles.ts
> +  flexDirection: 'row',
The default value of flex-direction is row, so if you can remove it explicitly

2023-08-27 10:27 UTC, Markusplay commented on src/components/common/ui/form/input-mui/Input.styles.ts
> +  ...(state === 'default' && {
you are using passing enum type so use InputState instead string as it was in `remark`
Same for error, success

2023-08-27 10:27 UTC, Markusplay commented on src/components/common/ui/form/input-mui/Input.styles.ts
> +      color: '#4A4A4A',
use palette

2023-08-27 10:27 UTC, Markusplay commented on src/components/common/ui/form/with-formik/input/FormikInput.stories.tsx
> +    readOnly: false,
also they both false by default

2023-08-27 10:54 UTC, Markusplay approved these changes

2023-09-03 16:32 UTC, ria0308 approved these changes
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣠⣄⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣠⣤⠤⣤⣀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⡾⠛⠉⢈⠉⠳⣤⣤⡶⠶⠶⠶⠶⠶⠶⠶⠶⠶⠟⢁⣤⣤⡀⠙⣷⡄⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⢸⡿⠁⣰⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⡆⠘⣷⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠘⣷⡀⠙⠿⠿⠟⠀⠀⠀⠀⠺⠶⠞⠓⠖⠛⠀⠀⠀⠀⠀⠙⠛⠋⠀⣼⡟⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⢀⡼⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⢿⣄⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⣼⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⢿⡆⠀
⠀⠀⠀⠀⠀⣀⠀⣾⠇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⣷⠀
⠀⠀⠀⡖⢶⠋⣿⣟⡀⠀⠀⠀⠀⠀⠀⠀⠐⣿⠷⢶⣤⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⡇
⠀⣤⣤⣷⢸⡀⣿⢛⡇⠀⠀⠀⠀⠀⠀⠀⠐⣌⠳⣍⣣⡽⣦⣄⠀⠀⢀⡴⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⡇
⠀⠻⣤⣉⣿⢻⡇⣼⠁⠀⠀⠀⣄⠀⠀⠀⠀⠸⣧⣤⣽⣿⡿⠿⠿⠿⡿⠀⠀⠀⠀⢀⡖⠀⠀⠀⠀⢸⡇
⢀⡴⣛⣫⡿⡟⢻⣝⣷⣦⣤⡤⣼⣷⣦⣄⡠⣤⠟⠉⠁⠀⠀⠀⠀⠀⠧⣴⣤⣠⠴⠛⠿⣷⢦⣄⢀⣿⠃
⠈⠉⢹⣋⡼⣇⣸⢻⣧⡿⠫⢦⣼⠉⠱⡀⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⠄⠀⠀⠈⠛⣿⣿⡏⠀
⠀⠀⠈⠉⠀⠙⠋⣰⢿⣁⣜⣿⠇⠀⠀⠙⠦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠤⠋⠀⠀⠀⣠⣶⡿⠛⠁⠀
⠀⠀⠀⠀⠀⠀⠠⠿⠴⠿⠛⠓⠶⢤⣄⣀⠀⠈⠑⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣴⠾⠟⠋⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⢿⣦⡀⠀⠀⠀⣼⠟⣿⡇⠀⠀⠀⠀⣠⡿⠃⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠛⠟⠻⠲⠞⠋⠀⠘⠓⠰⠆⠖⠚⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀

2023-09-03 22:12 UTC, merged