Feature/pagination
fictadvisor/fictadvisor-web pull request #512
Opened 2023-06-30 18:09 UTC by Markusplay

2023-06-30 19:34 UTC, andrewvitrenko requested changes

2023-06-30 19:34 UTC, andrewvitrenko commented on src/components/common/layout/header/components/desktop-header/DesktopHeader.styles.ts
> +import palette from '@/styles/theme/constants/palette';
replace with theme

2023-06-30 19:34 UTC, andrewvitrenko commented on src/components/common/layout/header/components/mobile-header/MobileHeader.styles.ts
> +import palette from '@/styles/theme/constants/palette';
replace with theme

2023-06-30 19:34 UTC, andrewvitrenko commented on src/components/common/ui/breadcrumbs-mui/Breadcrumbs.styles.ts
> +import palette from '@/styles/theme/constants/palette/palette';
replace with theme

2023-06-30 19:34 UTC, andrewvitrenko commented on src/components/common/ui/cards/floating-card/FloatingCard.styles.ts
> +import palette from 'src/styles/theme/constants/palette';
replace with `theme`

2023-06-30 19:34 UTC, andrewvitrenko commented on src/components/common/ui/column-chart/ColumnChart.styles.ts
> +import palette from '@/styles/theme/constants/palette';
replace with `theme`

2023-06-30 19:34 UTC, andrewvitrenko commented on src/components/common/ui/column-chart/utils/data.ts
> +import palette from '@/styles/theme/constants/palette';
replace with `theme`

2023-06-30 19:34 UTC, andrewvitrenko commented on src/components/common/ui/tab-mui/tab/Tab.styles.ts
> +import palette from '@/styles/theme/constants/palette';
replace with `theme`

2023-06-30 19:34 UTC, andrewvitrenko commented on src/components/common/ui/tab-mui/tab/Tab.styles.ts
>  import typography from '@/styles/theme/constants/typography';
remove typography

2023-06-30 19:34 UTC, andrewvitrenko commented on src/components/pages/search-pages/subject-search/SubjectSearchList.tsx
> +  const [subjectList, setSubjectList] = useState([]);
add generic type

2023-06-30 19:34 UTC, andrewvitrenko commented on src/components/pages/search-pages/subject-search/SubjectSearchList.tsx
> +      {subjectList &&
remove condition, you always have an array in state

2023-06-30 19:34 UTC, andrewvitrenko commented on src/components/pages/search-pages/subject-search/SubjectSearchPage.tsx
> +      SubjectsAPI.getAll.bind(null, queryObj, PAGE_SIZE, curPage),
```suggestion
      () => SubjectsAPI.getAll(queryObj, PAGE_SIZE, curPage),
```

2023-06-30 19:34 UTC, andrewvitrenko commented on src/components/pages/search-pages/subject-search/SubjectSearchPage.tsx
>  const SubjectSearchPage = () => {
```suggestion
const SubjectSearchPage: FC = () => {
```

2023-06-30 19:34 UTC, andrewvitrenko commented on src/components/pages/search-pages/subject-search/SubjectSearchPage.tsx
>    const [queryObj, setQueryObj] = useState(SubjectInitialValues);
add generic type

2023-06-30 19:34 UTC, andrewvitrenko commented on src/components/pages/search-pages/teacher-search/TeacherSearchList.tsx
> +  const [teacherList, setTeacherList] = useState([]);
add generic type

2023-06-30 19:34 UTC, andrewvitrenko commented on src/components/pages/search-pages/teacher-search/TeacherSearchList.tsx
> +      {teacherList &&
remove condition

2023-06-30 19:34 UTC, andrewvitrenko commented on src/components/pages/search-pages/teacher-search/TeacherSearchPage.tsx
> +    TeacherAPI.getAll.bind(null, queryObj, PAGE_SIZE, curPage),
```suggestion
    () => TeacherAPI.getAll(queryObj, PAGE_SIZE, curPage),
```

2023-06-30 19:34 UTC, andrewvitrenko commented on src/lib/api/subject/SubjectAPI.ts
>      const url = `/subjects?${search ? `search=${search}` : ''}${
rewrite with axios params

2023-06-30 19:34 UTC, andrewvitrenko commented on src/lib/api/teacher/TeacherAPI.ts
>      const url = `/teachers?${search ? `search=${search}` : ''}${
use axios params

2023-07-02 22:35 UTC, closed without merging

2023-07-02 22:36 UTC, Markusplay commented
due to huge amount of conflicts pull request will be done in new branch