enhancement:mui-tables & no-group section bug
fictadvisor/fictadvisor-web pull request #551
Opened 2023-07-05 22:46 UTC by kujo205

- merged separate mobile & desktop tables into 1
- changed Alerts to Toasts
- rewrote tables using Mui Grid (#300)
- fixed a bug with not displaying `no-group` section  (#550)

2023-07-06 11:43 UTC, ria0308 requested changes

2023-07-06 11:43 UTC, ria0308 commented on src/components/pages/account-page/components/group-tab/components/table/student-table/components/EditingColumn.tsx
> +        });
alert

2023-07-06 11:43 UTC, ria0308 commented on src/components/pages/account-page/components/group-tab/components/table/student-table/components/MobileDropdown.tsx
> +                student.role == UserGroupRole.STUDENT)) && (
move this logic to some const

2023-07-06 11:43 UTC, ria0308 commented on src/components/pages/account-page/components/group-tab/components/table/student-table/components/MobileDropdown.tsx
> +            student.role === UserGroupRole.CAPTAIN
move this logic to some const

2023-07-06 11:43 UTC, ria0308 commented on src/components/pages/account-page/components/group-tab/components/table/student-table/components/MobileDropdown.tsx
> +              student.role !== UserGroupRole.CAPTAIN && (
move this logic to some const

2023-07-06 11:43 UTC, ria0308 commented on src/components/pages/account-page/components/group-tab/components/table/student-table/StudentsTable.tsx
> +        toast.error('Здається ти ввів неправильні значення!', '', 3000);
coma after "здається"

2023-07-06 15:18 UTC, ria0308 approved these changes

2023-07-07 12:09 UTC, Markusplay approved these changes

2023-07-07 12:12 UTC, merged