feature/schedule-dropdown
fictadvisor/fictadvisor-web pull request #631
Opened 2023-08-15 18:15 UTC by Nanaier

2023-08-15 19:00 UTC, Markusplay requested changes

2023-08-15 19:05 UTC, Nanaier commented on src/components/pages/schedule-page/schedule-event-edit-section/components/schedule-dropdown/ScheduleDropdown.tsx
> +    console.log(icon ? true : false);
blyat - i forgot

2023-08-16 17:38 UTC, Markusplay approved these changes

2023-08-23 12:38 UTC, OleksandrHumeniuk approved these changes

2023-08-23 13:04 UTC, merged