enhancement/mui-404-page
fictadvisor/fictadvisor-web pull request #634
Opened 2023-08-18 17:06 UTC by Lil5166

2023-08-18 21:41 UTC, ria0308 commented on src/components/pages/404-page/NotFoundPage.styles.ts
> +};
import text styles from typography instead

2023-08-18 21:41 UTC, ria0308 commented on src/components/pages/404-page/NotFoundPage.tsx
do we need this?

2023-08-18 21:41 UTC, ria0308 commented on src/components/pages/404-page/NotFoundPage.module.scss
> -  width:69%;
do we need this file at all?

2023-08-19 20:11 UTC, ria0308 approved these changes

2023-08-22 20:52 UTC, kujo205 requested changes
![image](https://github.com/fictadvisor/fictadvisor-web/assets/86970828/9a23ef28-15e2-4730-a6e4-1bd768c6d6a6)
mobile version is not taken into account, use [breakpoints](https://mui.com/material-ui/customization/breakpoints/) to adjust to users screen size, u may find all the breakpoints in `src/styles/theme/constants/breakpoints/breakpoints.ts` file and example of usage is [here](https://github.com/fictadvisor/fictadvisor-web/blob/d3fd5748af6438c94c95b93c40ee1a82fc006478/src/components/pages/account-page/components/group-tab/components/text-area-popup/TextAreaPopup.styles.ts#L12)

2023-09-02 08:57 UTC, kujo205 approved these changes

2023-09-03 16:18 UTC, Yevheniy2020 commented on src/components/pages/404-page/NotFoundPage.styles.ts
> +  typography: { desktop: 'h5', mobile: 'body2' },
you need replace all typography as 
import theme from '@/styles/theme';
`typography: { desktop: theme.typography.h5, mobile:  ...},`

2023-09-03 16:22 UTC, ria0308 commented on src/components/pages/404-page/NotFoundPage.styles.ts
> +  marginTop: { desktop: '64px', mobile: '63px' },
change to 64px in all cases

2023-09-03 16:22 UTC, ria0308 commented on src/components/pages/404-page/NotFoundPage.tsx
> +              maxWidth: '300px',
move to styles.ts

2023-09-03 16:22 UTC, ria0308 commented on src/components/pages/404-page/NotFoundPage.tsx
> +              maxWidth: '300px',
move to styles.ts

2023-09-03 18:28 UTC, Yevheniy2020 approved these changes

2023-09-04 10:27 UTC, merged