enhancement/login-page-mui
fictadvisor/fictadvisor-web pull request #648
Opened 2023-08-27 13:55 UTC by yablonya

2023-08-27 15:59 UTC, Markusplay requested changes

2023-08-27 15:59 UTC, Markusplay commented on src/components/pages/login-page/LoginPage.styles.ts
> +  borderColor: '#FAFAFA',
use palette

2023-08-27 15:59 UTC, Markusplay commented on src/components/pages/login-page/components/login-form-block/LoginFormBlock.styles.ts
> +    borderColor: '#FAFAFA',
use palette

2023-08-27 15:59 UTC, Markusplay commented on src/components/pages/login-page/components/login-form-block/LoginFormBlock.styles.ts
> +    borderColor: '#FAFAFA',
use palette

2023-08-27 15:59 UTC, Markusplay commented on src/components/pages/login-page/components/login-form-block/LoginFormBlock.styles.ts
> +  color: '#D4D4D4',
use palette

2023-08-27 15:59 UTC, Markusplay commented on src/components/pages/login-page/components/login-form-block/LoginFormBlock.styles.ts
> +  fontWeight: 500,
use typography

2023-08-27 15:59 UTC, Markusplay commented on src/components/pages/login-page/components/login-form-block/LoginFormBlock.tsx
use new `mui` Button component

2023-08-27 15:59 UTC, Markusplay commented on src/components/pages/login-page/components/logo-register-block/LogoRegisterBlock.tsx
> +      <Typography variant="h3" sx={styles.registerText}>
as your font doesn't changes with width size, remove styles for fonts in `registerText` and set correct `variant` for `Typography`

2023-08-27 15:59 UTC, Markusplay commented on src/components/pages/login-page/components/login-form-block/LoginFormBlock.tsx
> +      <Typography sx={sxStyles.mobileText}>Ти ще не з нами? </Typography>
you say `mobileText` but it exist even on dekstop. Rename style

2023-08-27 15:59 UTC, Markusplay commented on src/components/pages/login-page/components/login-form-block/LoginFormBlock.tsx
> +      <Typography variant="h3" sx={sxStyles.loginHeader}>
as your font doesn't changes with width size, remove styles for fonts in `loginHeader` and set correct `variant` for `Typography`

2023-08-27 15:59 UTC, Markusplay commented on src/components/pages/login-page/components/logo-register-block/LogoRegisterBlock.tsx
use new `mui` Button component

2023-08-27 15:59 UTC, Markusplay commented on src/components/pages/login-page/components/login-form/LoginForm.tsx
you removed styles for input, wtf ?

2023-08-27 15:59 UTC, Markusplay commented on src/components/pages/login-page/LoginPage.styles.ts
> +export const loginPage__content: SxProps<Theme> = {
we write styles in camelCase

2023-08-27 15:59 UTC, Markusplay commented on src/components/pages/login-page/LoginPage.styles.ts
> +  flexDirection: 'row',
flexDirection is row by default

2023-08-27 20:43 UTC, Markusplay requested changes

2023-08-27 20:43 UTC, Markusplay commented on src/components/pages/login-page/LoginPage.styles.ts
> +    backgroundSize: '100% 100%',
duplicate

2023-08-27 20:43 UTC, Markusplay commented on src/components/pages/login-page/LoginPage.styles.ts
> +    width: '100%',
duplicate

2023-08-27 20:43 UTC, Markusplay commented on src/components/pages/login-page/components/login-form-block/LoginFormBlock.styles.ts
> +  },
duplicate

2023-08-27 22:09 UTC, Markusplay requested changes

2023-08-27 22:09 UTC, Markusplay commented on src/components/pages/login-page/components/login-form-block/LoginFormBlock.module.scss
> +
do you use this styles anywhere ?

2023-08-28 09:44 UTC, Markusplay approved these changes

2023-08-30 10:49 UTC, igaryakqwe approved these changes

2023-08-30 16:15 UTC, merged