enchancement/account-page
fictadvisor/fictadvisor-web pull request #690
Opened 2023-09-08 09:09 UTC by ria0308

2023-09-25 20:24 UTC, Markusplay requested changes

2023-09-25 20:24 UTC, Markusplay commented on src/components/common/ui/form/input/index.ts
wtf

2023-09-25 20:24 UTC, Markusplay commented on src/components/pages/account-page/components/general-tab/GeneralTab.module.scss
remove comments

2023-09-25 20:24 UTC, Markusplay commented on src/components/pages/account-page/components/general-tab/GeneralTab.styles.ts
> +  border: '2px solid $background-dark-35',
use color from palette

2023-09-25 20:24 UTC, Markusplay commented on src/components/pages/account-page/components/general-tab/components/contacts-block/constants/index.ts
I would say it is "validation" folder, not "constants"

2023-09-25 20:24 UTC, Markusplay commented on src/components/pages/account-page/components/group-tab/GroupTab.tsx
> +      </Box>
Do we really need this `Box` wrap here ?

2023-09-25 20:24 UTC, Markusplay commented on src/components/pages/account-page/types/index.ts
> +}
Due to enum naming conventions, as you did above, make keys with upper case too.

2023-09-25 20:24 UTC, Markusplay commented on src/components/pages/account-page/components/selective-tab/components/opened-selective/OpenedSelective.tsx
If you don't see what refactor, better to remove this todo than adding new comment

2023-09-25 20:24 UTC, Markusplay commented on src/components/pages/account-page/components/security-tab/components/change-password-form/ChangePasswordForm.styles.ts
> +};
use typography

2023-09-25 20:24 UTC, Markusplay commented on src/components/pages/account-page/components/security-tab/SecurityTab.tsx
> +        <Divider sx={styles.divider}></Divider>
```suggestion
        <Divider sx={styles.divider}/>
      
```

2023-09-25 20:24 UTC, Markusplay commented on src/components/pages/account-page/components/security-tab/SecurityTab.tsx
> +        ></Divider>
make it self close

2023-09-25 20:24 UTC, Markusplay commented on src/components/pages/account-page/components/security-tab/SecurityTab.tsx
> +          ></Divider>
make it self close

2023-09-25 20:24 UTC, Markusplay commented on src/components/pages/account-page/components/security-tab/SecurityTab.tsx
> +    <Box>
remove extra wrapper

2023-09-25 20:24 UTC, Markusplay commented on src/components/pages/account-page/components/security-tab/SecurityTab.styles.ts
> +  padding: '12px 44.5px',
make it 12px 45px :)

2023-09-25 20:24 UTC, Markusplay commented on src/components/pages/account-page/components/group-tab/components/no-group-block/NoGroupBlock.tsx
> +            <Box></Box>
wtf

2023-09-25 20:24 UTC, Markusplay commented on src/components/pages/account-page/components/group-tab/components/no-group-block/NoGroupBlock.tsx
> +            <Box sx={muiStyles.divisionWhite}></Box>
```suggestion
            <Box sx={muiStyles.divisionWhite}/>
```

2023-09-25 20:24 UTC, Markusplay commented on src/components/pages/account-page/components/group-tab/components/no-group-block/NoGroupBlock.tsx
> +            <Box sx={muiStyles.divisionWhite}></Box>
```suggestion
            <Box sx={muiStyles.divisionWhite}/>
```

2023-09-25 22:14 UTC, Markusplay commented on src/components/pages/account-page/components/general-tab/components/personal-info/PersonalInfo.tsx
> +                sx={isMobile ? styles.buttonPadding : {}}
```suggestion
                sx={isMobile && styles.buttonPadding}
```

2023-09-25 22:19 UTC, Yevheniy2020 commented on src/components/pages/account-page/components/general-tab/components/personal-info/PersonalInfo.tsx
> +                sx={isMobile ? styles.buttonPadding : {}}
![image](https://github.com/fictadvisor/fictadvisor-web/assets/68693183/defd0485-e1e1-443d-91c7-4092e0900cb9)

2023-09-25 22:29 UTC, Markusplay approved these changes

2023-09-26 17:56 UTC, guywhodiesfirst reviewed
very small margin between header and students list
also, the font of header should be bold
![StudentList](https://github.com/fictadvisor/fictadvisor-web/assets/144242408/180f3450-a308-496b-a16c-452707943718)
![StudentList2](https://github.com/fictadvisor/fictadvisor-web/assets/144242408/48566772-27c3-4203-985c-016092e91c94)

2023-09-26 18:01 UTC, guywhodiesfirst commented
some students profile pics are displayed incorrectly - depending on page scale, they are compressed vertically or horizontally
![vfkbq](https://github.com/fictadvisor/fictadvisor-web/assets/144242408/bd6b5b4c-1d66-4b4f-ab42-964ae698929f)
![vfkbq1](https://github.com/fictadvisor/fictadvisor-web/assets/144242408/9aeb9a67-60c6-4014-b4ca-869e43ca5d4d)

2023-09-26 20:47 UTC, IK-24KudinaDiana commented
Home -> Security
there should be no validation on the password field, validation of the password field does not work correctly. (see screenshots)
On prod: there may be a Ukrainian-English password, but it cannot be updated to the same Ukrainian-English one
![photo_2023-09-26_23-37-12](https://github.com/fictadvisor/fictadvisor-web/assets/128691252/f095574a-f635-4d49-8ad4-c95f1e775250)
![photo_2023-09-26_23-37-01](https://github.com/fictadvisor/fictadvisor-web/assets/128691252/66db05f3-49bf-48a4-80dc-472ca89b1b6f)
![photo_2023-09-26_23-36-44](https://github.com/fictadvisor/fictadvisor-web/assets/128691252/357f2c3d-1643-490b-a27c-ef366fca49a2)
![photo_2023-09-26_23-36-39](https://github.com/fictadvisor/fictadvisor-web/assets/128691252/fe81aab3-b00e-4858-9488-ba96a99a787b)
![photo_2023-09-26_23-36-35](https://github.com/fictadvisor/fictadvisor-web/assets/128691252/b0b6e23a-3de9-49d2-9803-a5bee23544af)
![1](https://github.com/fictadvisor/fictadvisor-web/assets/128691252/c4d1fca1-34bc-45e0-9880-3a63d9adc8c1)

2023-09-28 17:20 UTC, kovaliovev commented
Request card does not match the [design](https://www.figma.com/file/FHBiKogMc9VzGWojaQxA9c/%F0%9F%94%A52.1?type=design&node-id=3230-24590&mode=design&t=JUQkIyIF9ChewhBv-4).
![photo_2023-09-28_20-18-16](https://github.com/fictadvisor/fictadvisor-web/assets/111194749/d1867a15-4af5-4ba0-9638-1228be85c8a7)
![Screenshot_1](https://github.com/fictadvisor/fictadvisor-web/assets/111194749/8a78ad76-5fbb-419d-af7e-1d3c06a49501)

2023-09-28 17:24 UTC, kovaliovev commented
Opportunity to give student with role "Заст. старости" this role again.
![image](https://github.com/fictadvisor/fictadvisor-web/assets/111194749/45fb96c2-c7ef-4c42-a4a6-f074f0c398d9)

2023-09-28 17:28 UTC, kovaliovev commented
Request denied error does not match the [design](https://www.figma.com/file/FHBiKogMc9VzGWojaQxA9c/%F0%9F%94%A52.1?type=design&node-id=3270-25036&mode=design&t=JUQkIyIF9ChewhBv-4).
![image](https://github.com/fictadvisor/fictadvisor-web/assets/111194749/57e679a8-5490-4fd4-830e-6be4f1327bf3)
![image](https://github.com/fictadvisor/fictadvisor-web/assets/111194749/2e416d99-7d89-45d3-9448-53ddc271fe90)

2023-09-28 17:33 UTC, kovaliovev commented
Footer does not match the [design](https://www.figma.com/file/FHBiKogMc9VzGWojaQxA9c/%F0%9F%94%A52.1?type=design&node-id=2774-21969&mode=design&t=JUQkIyIF9ChewhBv-4).
![image](https://github.com/fictadvisor/fictadvisor-web/assets/111194749/d3e12359-1bcc-4ed5-bac9-4d64ae242277)
![image](https://github.com/fictadvisor/fictadvisor-web/assets/111194749/280c7d49-5fa1-4e92-a58e-3a98cd5819d9)

2023-10-01 14:15 UTC, kovaliovev commented
Too long lines on Security tab. [design](https://www.figma.com/file/FHBiKogMc9VzGWojaQxA9c/%F0%9F%94%A52.1?type=design&node-id=1584-8060&mode=design&t=oJ4Sx8TyznHyCyqO-4).
![Screenshot_1](https://github.com/fictadvisor/fictadvisor-web/assets/111194749/e9cba772-54b8-435e-8ed6-c55a244c64c1)
![Screenshot_2](https://github.com/fictadvisor/fictadvisor-web/assets/111194749/9a9e6e0a-49e9-4bd9-8af3-448d2a9019f5)

2023-10-01 14:16 UTC, kovaliovev commented
Too long input fields on Security tab on mobile.
![image](https://github.com/fictadvisor/fictadvisor-web/assets/111194749/3021f46c-2031-4038-8cde-3d6779f48e21)

2023-10-02 07:40 UTC, IK-24KudinaDiana commented
![photo_2023-10-02_10-39-11](https://github.com/fictadvisor/fictadvisor-web/assets/128691252/769e314b-1e97-4977-814b-acac5ed142f7)
The headman cannot become a deputy headman

2023-10-02 07:58 UTC, IK-24KudinaDiana commented
![figma](https://github.com/fictadvisor/fictadvisor-web/assets/128691252/88d4e94c-7bf5-4752-9e60-2343307176d8)
![real result](https://github.com/fictadvisor/fictadvisor-web/assets/128691252/526fbb92-2d7f-406f-96fa-25cdc06fd97e)
The first screenshot is a figma, the second is the site.
Inconsistency in the name and appearance of the buttons

2023-10-02 08:02 UTC, IK-24KudinaDiana commented
![2023-10-02_10-54](https://github.com/fictadvisor/fictadvisor-web/assets/128691252/63c41a2b-7cfd-4a96-b2fd-2da5acd0d527)
![Знімок екрана 2023-10-02 110018](https://github.com/fictadvisor/fictadvisor-web/assets/128691252/bd997f74-8349-4b4e-b473-bd682b7043f6)
Inconsistency with figma template: no icon, no username, close button too low.

2023-10-02 08:30 UTC, IK-24KudinaDiana commented
![photo_2023-10-02_11-28-39](https://github.com/fictadvisor/fictadvisor-web/assets/128691252/51077a56-fc36-41b1-9fb9-29fa85f9c940)
The first letter is small.

2023-10-02 09:08 UTC, IK-24KudinaDiana commented
![photo_2023-10-02_12-06-47](https://github.com/fictadvisor/fictadvisor-web/assets/128691252/afd502bb-9753-4034-8230-24ebe147ce51)
There is a template test under the password, but there is none on the site.

2023-10-02 13:45 UTC, guywhodiesfirst commented
there is still a problem when some user profile pics are stretching depending on a page scale
https://github.com/fictadvisor/fictadvisor-web/assets/144242408/26bb2660-7492-489d-ac0e-3cf3224c7038

2023-10-02 20:12 UTC, kovaliovev commented
First text is center-align, when second is left-align.
![image](https://github.com/fictadvisor/fictadvisor-web/assets/111194749/3dea306c-029f-4019-b3db-e4ed0bb23923)

2023-10-02 20:14 UTC, kovaliovev commented
No margin between emails and buttons at 1200-1225 px window width.
![image](https://github.com/fictadvisor/fictadvisor-web/assets/111194749/114452e6-ca48-4af3-9cbf-0127cd6eacef)

2023-10-02 20:57 UTC, kovaliovev commented
Group tab does not match the [design](https://www.figma.com/file/FHBiKogMc9VzGWojaQxA9c/%F0%9F%94%A52.1?type=design&node-id=1922-11604&mode=design&t=TL9EfZ0E7cqtu2aU-4).
![image](https://github.com/fictadvisor/fictadvisor-web/assets/111194749/71bf880c-c6f9-4f5f-820b-10d2d45154ec)
![image](https://github.com/fictadvisor/fictadvisor-web/assets/111194749/a6897b20-a681-4441-8f24-b621a6ab3f0c)

2023-10-02 22:37 UTC, kol-oss commented
**Button("Додати посилання") incorrectly changes size on the breakpoint 1440**

**SIZE:** 1440 * 1020;

**Video:**

https://github.com/fictadvisor/fictadvisor-web/assets/62239358/bcb33051-96d0-49d8-8dbf-61747dc6c828

**Actual (deploy):**

![image](https://github.com/fictadvisor/fictadvisor-web/assets/62239358/e1efb658-566d-454d-a711-2ced27d4c0b2)

![image](https://github.com/fictadvisor/fictadvisor-web/assets/62239358/5fd3fe77-ab31-4f3c-bb37-1f78393353a4)

**Expected ([figma](https://www.figma.com/file/FHBiKogMc9VzGWojaQxA9c/%F0%9F%94%A52.1?type=design&node-id=299%3A58&mode=design&t=1SwkEEGLo80oTnBV-1)):**

![image](https://github.com/fictadvisor/fictadvisor-web/assets/62239358/60f77284-d2de-483c-a160-06facedf678d)

2023-10-03 13:26 UTC, merged