feature/admin-menu-panel
fictadvisor/fictadvisor-web pull request #836
Opened 2023-11-08 20:08 UTC by yablonya

2023-11-08 23:21 UTC, Markusplay requested changes

2023-11-08 23:21 UTC, Markusplay commented on src/components/common/layout/page-layout/PageLayout.tsx
AdminPanelLayout needs to be create, don't touch default layout

2023-11-09 18:00 UTC, Markusplay approved these changes

2023-11-10 07:56 UTC, kovaliovev commented
✔ qa approved

2023-11-10 18:45 UTC, merged