added main admin page
fictadvisor/fictadvisor-web pull request #843
Opened 2023-11-11 18:19 UTC by Markusplay

2023-11-11 19:09 UTC, yablonya approved these changes

2023-11-12 11:44 UTC, AnastasiaLytvyn approved these changes
"Головна сторінка" should not be highlighted, there is nothing to highlight for this page
 you need to add a new path for the "Головна сторінка"

2023-11-12 12:45 UTC, AnastasiaLytvyn requested changes
Change background color

2023-11-14 18:51 UTC, AnastasiaLytvyn approved these changes
qa approve

2023-11-16 18:04 UTC, merged