bugfix: profile photo on account page
fictadvisor/fictadvisor-web pull request #846
Opened 2023-11-13 18:56 UTC by sifes

closed #768

2023-11-13 22:42 UTC, Yevheniy2020 commented on src/components/common/ui/alert/Alert.styles.ts
> +    color: 'grey.800',
color: theme.palette.grey[800]

2023-11-13 22:42 UTC, Yevheniy2020 commented on src/components/common/ui/alert/Alert.styles.ts
> +    margin: '0 0 0 0',
margin: 0

2023-11-13 22:42 UTC, Yevheniy2020 approved these changes

2023-11-14 08:47 UTC, kol-oss commented
qa approved

2023-11-16 17:18 UTC, Markusplay requested changes

2023-11-16 17:18 UTC, Markusplay commented on src/components/pages/account-page/components/general-tab/components/change-avatar-window/components/avatar-dropzone/utils/handleFileSelect.ts
> +      2000000,
make time normal as it was

2023-11-16 17:57 UTC, merged