seo/schedule-page-description
fictadvisor/fictadvisor-web pull request #847
Opened 2023-11-14 12:41 UTC by yablonya

2023-11-15 20:50 UTC, kujo205 commented on src/components/pages/schedule-page/SchedulePage.tsx
> +       пари, переходь до конференцій, додавай власні та змінюй вже існуючі події."
```suggestion
       пари, переходь до конференцій, додавай власні та змінюй вже наявні події."
```

syntax error

2023-11-15 20:51 UTC, kujo205 requested changes

2023-11-15 20:51 UTC, kujo205 commented on src/components/pages/schedule-page/SchedulePage.tsx
> +       пари, переходь до конференцій, додавай власні та змінюй вже існуючі події."
```suggestion
      description="FICT Advisor представляє оновлений розклад занять для студентів ФІОТу КПІ. Переглядай та фільтруй
       пари, переходь до конференцій, додавай власні та змінюй вже наявні події."
```
syntax error

2023-11-15 20:58 UTC, kujo205 approved these changes

2023-11-16 11:23 UTC, kovaliovev commented
✔ qa approved

2023-11-16 11:29 UTC, Markusplay approved these changes

2023-11-16 11:30 UTC, merged