bugfix/selective-checkbox
fictadvisor/fictadvisor-web pull request #852
Opened 2023-11-15 21:08 UTC by M-Rybalko

2023-11-16 18:13 UTC, Markusplay approved these changes

2023-11-17 11:53 UTC, papiroskada commented
qa approved

2023-11-17 21:22 UTC, AnastasiaLytvyn commented
shedule table is reloaded after chechking and unchecking all type of subjects

2023-11-18 14:35 UTC, Markusplay requested changes

2023-11-18 14:35 UTC, Markusplay commented on src/components/pages/schedule-page/SchedulePage.tsx
> +    };
extract out of useEffect

2023-11-18 14:35 UTC, Markusplay commented on src/store/schedule/useSchedule.ts
> +      }
remove console logs

2023-11-18 15:40 UTC, papiroskada commented
qa approved

2023-11-20 17:01 UTC, AnastasiaLytvyn approved these changes
qa approve

2023-11-20 17:05 UTC, Markusplay approved these changes

2023-11-21 08:12 UTC, merged